name: Test

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: marshall-ku/workflows/setup_pnpm@master
            - name: Run script
              run: pnpm start
