name: Test

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: marshall-ku/workflows/setup_pnpm@master
            - name: Run script
              run: pnpm start
    trigger:
        runs-on: ubuntu-latest
        steps:
            - run: |
                  gh api /repos/marshall-ku/npm-script/dispatches \
                  -X POST \
                  -F event_type=my-event-type \
                  -F client_payload={"passed": false, "message": "Hi there"}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # send:
    #     uses: marshall-ku/workflows/.github/workflows/send_notification.yml@master
    #     with:
    #         succeed: true
    #         message: "Testing workflow"
    #         title: "Hello there"
    #         color: "3108265"
    #     secrets:
    #         url: ${{ secrets.DISCORD_WEBHOOK_URI }}
    check-version:
        runs-on: ubuntu-latest
        steps:
            - uses: marshall-ku/workflows/check_version@master
              id: check-version
            - uses: marshall-ku/workflows/create_tag_release@master
              if: ${{ steps.check-version.outputs.version != '' }}
              with:
                  tag: ${{ steps.check-version.outputs.version }}
