name: Test

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: marshall-ku/workflows/setup_pnpm@master
            - name: Run script
              run: pnpm start
    send:
        uses: marshall-ku/workflows/.github/workflows/send_notification.yml@master
        with:
            status: ${{ contains(join(needs.*.result, ','), 'failure') }}
            message: "CI job failed - pull request"
        secrets:
            url: ${{ secrets.DISCORD_WEBHOOK_URI }}
