name: Test

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check test result
              id: check-test-result
              run: |
                  OUPTUT=$(node console.js)
                  echo "$OUPTUT" >> "$GITHUB_ENV"
            - name: Create commit comment
              if: ${{ !cancelled() }}
              uses: peter-evans/commit-comment@v3
              with:
                  body: |
                      Hi there.
                      This is your table.

                      ${{ env.RESULT }}

                      Thanks.
    create-pr:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: echo $(date) > temp.txt
            - run: bash .github/scripts/commit.sh
              env:
                  FILES: temp.txt
                  MESSAGE: "Update visual regression test results"
                  PREVENT_PUSH: true
            - uses: peter-evans/create-pull-request@v6
              with:
                  title: "[Example] Update report"
                  branch: visual-regression-${{ github.ref_name }}
                  delete-branch: true
                  labels: |
                      automated
                  reviewers: |
                      ${{ vars.REVIEWERS }}
    # trigger:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - run: |
    #               gh api \
    #                 --method POST \
    #                 -H "Accept: application/vnd.github+json" \
    #                 -H "X-GitHub-Api-Version: 2022-11-28" \
    #                 /repos/marshall-ku/npm-script/dispatches \
    #                   --field event_type=my-event-type \
    #                   --field client_payload[passed]=false \
    #                   --field client_payload[message]="Testing workflow"
    #           env:
    #               GITHUB_TOKEN: ${{ secrets.TOKEN }}

    send:
        uses: marshall-ku/workflows/.github/workflows/call.yaml@master
        with:
            repository: ${{ github.repository }}
            title: "Hi there"

    check-version:
        runs-on: ubuntu-latest
        steps:
            - uses: marshall-ku/workflows/check_version@master
              id: check-version
            - uses: marshall-ku/workflows/create_tag_release@master
              if: ${{ steps.check-version.outputs.version != '' }}
              with:
                  tag: ${{ steps.check-version.outputs.version }}

    greeting:
        runs-on: ubuntu-latest
        steps:
            - uses: marshall-ku/workflows/greeting@master
              id: greeting
              with:
                  name: "Marshall"
            - run: |
                  echo "MESSAGE: ${{ steps.greeting.outputs.message }}"
                  echo "VERSION: ${{ steps.greeting.outputs.version }}"
