name: Test

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: marshall-ku/workflows/setup_pnpm@master
            - name: Run script
              run: pnpm start
    send:
        uses: marshall-ku/workflows/.github/workflows/send_notification.yml@master
        with:
            succeed: true
            message: "Testing workflow"
            title: "Hello there"
            color: "3108265"
        secrets:
            url: ${{ secrets.DISCORD_WEBHOOK_URI }}
