name: Test

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: marshall-ku/workflows/setup_pnpm@master
            - name: Run script
              run: pnpm start
    trigger:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/github-script@v6
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
              with:
                  script: |
                      github.rest.actions.createWorkflowDispatch({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          workflow_id: 'dispatch.yml',
                          ref: 'master',
                          event_type: 'my-event-type',
                          client_payload: {
                              passed: false,
                              message: 'Hi'
                          }
                      })

    # send:
    #     uses: marshall-ku/workflows/.github/workflows/send_notification.yml@master
    #     with:
    #         succeed: true
    #         message: "Testing workflow"
    #         title: "Hello there"
    #         color: "3108265"
    #     secrets:
    #         url: ${{ secrets.DISCORD_WEBHOOK_URI }}
    check-version:
        runs-on: ubuntu-latest
        steps:
            - uses: marshall-ku/workflows/check_version@master
              id: check-version
            - uses: marshall-ku/workflows/create_tag_release@master
              if: ${{ steps.check-version.outputs.version != '' }}
              with:
                  tag: ${{ steps.check-version.outputs.version }}
